```{r echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# 1.27-b4
```{r}

# 1.27-b4
file_path <- "CH01PR27.txt"
data <- read.table(file_path)
y <- data$V1
x <- data$V2
n <- nrow(data)

model <- lm(y ~ x, data = data)
residual <- residuals(model)
sum(residual ** 2) / (n - 2)
```
$\hat{\sigma}^2 = s^2 = 66.8$

# 2.28-a
```{r}

# 2.28-a
summary_model <- summary(model)
mse <- summary_model$sigma ** 2
beta <- coefficients(model)
beta_0 <- beta[1]
beta_1 <- beta[2]
x_h <- 60
x_bar <- mean(x)

y_hat_h <- beta_0 + beta_1 * x_h
se_y_hat_h <- sqrt(mse * (1 / n + (x_h - x_bar) ** 2 / sum((x - x_bar) ** 2)))
t_value <- qt(0.975, df = 58)

lower_bound <- y_hat_h - t_value * se_y_hat_h
upper_bound <- y_hat_h + t_value * se_y_hat_h
cat("[", lower_bound, ", ", upper_bound, "]", sep = "")
```
We are 95% confident that the mean of muscle mass of age 60 women is within this interval.

# 2.28-b
```{r}

# 2.28-b
s_Y_h_new <- sqrt(mse * (1 + 1 / n + (x_h - x_bar) ** 2 / sum((x - x_bar) ** 2)))
lower_bound <- y_hat_h - t_value * s_Y_h_new
upper_bound <- y_hat_h + t_value * s_Y_h_new

cat("[", lower_bound, ", ", upper_bound, "]", sep = "")
```
The prediction interval should be precise because it tell us where we expect the individual values to land. However, the range is large. ??

# Appendix
```{r ref.label=knitr::all_labels(), echo=TRUE, eval=FALSE}
```